const moreWildDares = [
    "Send a flirty text to the last person you messaged.",
    "Wear your shirt inside out for the rest of the game.",
    "Dance like a ballerina for one minute.",
    "Let someone give you a makeover blindfolded.",
    "Talk in baby talk until your next turn.",
    "Do your best impression of someone in the room.",
    "Wear a funny hat or wig for the next hour.",
    "Call a random contact and confess your love for pizza.",
    "Do 30 jumping jacks without stopping.",
    "Attempt to breakdance for 30 seconds.",
    "Let someone post an embarrassing photo of you online.",
    "Eat a spoonful of mustard or hot sauce.",
    "Do your best runway walk across the room.",
    "Let the group come up with a new nickname for you and use it for the next hour.",
    "Sing everything you say for the next 10 minutes.",
    "Balance a book on your head while walking across the room.",
    "Wear socks on your hands for the next 10 minutes.",
    "Attempt to lick your elbow.",
    "Do a silly dance in the middle of the room.",
    "Let someone tickle you for 30 seconds.",
    "Speak only in rhymes until your next turn.",
    "Make a funny face and hold it for 20 seconds.",
    "Try to do a handstand or cartwheel.",
    "Do your best evil laugh.",
    "Wear your clothes backward for the next hour.",
    "Take a silly selfie and send it to a random contact.",
    "Do 10 push-ups while singing your favorite song.",
    "Pretend to be a cat for the next 2 minutes.",
    "Try to juggle three random objects.",
    "Do your best robot dance.",
    "Let someone write a funny message on your forehead with a marker.",
    "Eat a raw onion slice.",
    "Talk without closing your mouth for one minute.",
    "Do your best impression of a famous movie scene.",
    "Pretend to be a statue for 1 minute.",
    "Sing the chorus of your favorite song in a funny voice.",
    "Wear sunglasses inside the house until your next turn.",
    "Try to burp the alphabet.",
    "Speak like a pirate until your next turn.",
    "Do a dramatic reading of a children’s book.",
    "Wear underwear on your head for the next 10 minutes.",
    "Make up a rap about someone in the group.",
    "Do your best runway model pose and hold it.",
    "Take a funny video of yourself and post it online.",
    "Do your best impression of an animal chosen by the group.",
    "Let someone draw a funny mustache on your face.",
    "Speak only in movie quotes for the next 5 minutes.",
    "Wear a goofy hat for the rest of the game.",
    "Try to touch your nose with your tongue.",
    "Do 20 squats while telling a joke.",
    "Make up a silly dance and teach it to everyone."
  ];
  
  export default moreWildDares