const moreWildTruths =[
    "Have you ever pretended to like someone just to avoid conflict?",
    "Do you secretly judge your friends’ life choices?",
    "Have you ever been the toxic person in a relationship?",
    "Would you date someone just for money or status?",
    "Have you ever lied to a therapist or doctor?",
    "Do you think you're better than most people you know?",
    "What's one social norm you think is complete nonsense?",
    "Have you ever sabotaged someone else’s opportunity?",
    "Would you ever cheat if you knew you wouldn’t get caught?",
    "What’s one belief you have that your parents would be ashamed of?",
    "Have you ever used someone emotionally for your own gain?",
    "Do you think most people are inherently selfish?",
    "Have you ever stolen something from someone you know?",
    "What's something you think everyone lies about?",
    "Would you stay silent if you witnessed injustice and it didn't involve you?",
    "Have you ever let someone else take the blame for something you did?",
    "Do you believe in revenge?",
    "Would you marry someone you didn’t love if they offered financial security?",
    "Have you ever used emotional manipulation to win an argument?",
    "What’s the biggest double life you’ve ever led?",
    "Do you think some people are just born evil?",
    "Have you ever ruined someone’s reputation out of jealousy or anger?",
    "Would you report your best friend if they committed a serious crime?",
    "Do you ever feel proud of being petty?",
    "What’s one thing you’ve done that you'd never admit publicly?",
    "Have you ever ghosted someone who really cared about you?",
    "Do you believe morality is relative?",
    "Have you ever intentionally led someone on for attention?",
    "Do you secretly wish bad things on people you envy?",
    "What's a popular cause or movement you think is overrated?",
    "Have you ever watched someone suffer and done nothing?",
    "What type of people do you secretly dislike?",
    "Would you betray your values to get ahead in your career?",
    "Have you ever faked a friendship for personal benefit?",
    "Do you think monogamy is natural?",
    "Have you ever felt like your life would be better if someone close to you didn’t exist?",
    "What’s the cruelest thing you’ve ever thought but didn’t say?",
    "Do you think most people are actually racist or prejudiced deep down?",
    "Have you ever been proud of breaking someone’s heart?",
    "Would you support something unethical if it benefited your family?",
    "Have you ever lied about your mental health?",
    "Have you ever told a lie that changed someone's life for the worse?",
    "Do you think loyalty is overrated?",
    "Have you ever made fun of someone’s appearance behind their back?",
    "Would you rather be feared or loved?",
    "Do you think people exaggerate their trauma for attention?",
    "Have you ever bullied someone — even subtly?",
    "What’s a value you pretend to care about but secretly don’t?",
    "Would you ever sell out your beliefs for fame?",
    "Have you ever wished someone close to you would fail?",
    "What’s one truth you’ll never admit to your partner?",
    "Do you believe people in poverty are always victims?",
    "Have you ever secretly hoped someone would break up so you could have a chance with them?",
    "Do you think love is overrated?",
    "What do you actually think about the way your friends live their lives?",
    "Would you end a long friendship to be with your crush?",
    "Do you think forgiveness is necessary in all situations?",
    "Have you ever used someone else's vulnerability against them?",
    "Would you be okay with never telling the full truth to your family?",
    "Have you ever resented someone for their success?",
    "Do you think most people would abandon their principles for power?",
    "What's your most politically incorrect opinion?",
    "Would you lie to get someone fired if it helped your career?",
    "What’s one belief you have that would shock your friends?",
    "Do you think some people deserve to be unhappy?",
    "Would you hide a family secret if it protected your reputation?",
    "Have you ever enjoyed watching someone you dislike struggle?",
    "Do you think you’re emotionally manipulative?",
    "Would you pretend to support a cause you don’t believe in for likes or followers?",
    "What’s something you’re deeply ashamed of but never told anyone?",
    "Have you ever laughed at someone else’s pain?",
    "Do you secretly think you’re more attractive than your friends?",
    "Have you ever stayed in a relationship just for sex or convenience?",
    "Would you ever cross a moral line if no one would ever know?",
    "Have you ever lied during a job interview to get ahead?",
    "Would you rather live a happy lie or face a painful truth?",
    "What kind of people do you think don’t deserve a second chance?",
    "Have you ever wished someone would fail just to feel better about yourself?",
    "Have you ever pretended to believe something just to fit in?",
    "Do you think your life is more valuable than a stranger’s?"
  ]
  
  export default moreWildTruths;